src/Entity/SavRetour/Commande.php
<?php

namespace App\Entity\SavRetour;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Ex table TR_SAVRETOUR_COMMANDE
 *
 * @ORM\Entity(repositoryClass="App\Repository\SavRetour\CommandeRepository")
 */
class Commande
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\SavRetour\CommandeLigne", mappedBy="commande", orphanRemoval=true)
     * @ORM\OneToMany(targetEntity="App\Entity\SavRetour\Picking", mappedBy="num_cmd", orphanRemoval=true)
     */
    private $num_cmd;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $demandeur;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $magasin_cedant;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $destination;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="boolean")
     */
    private $solde = false;

    /**
     * @ORM\Column(type="string", length=35, unique=true)
     */
    private $num_commande;

    public function __construct()
    {
        $this->num_cmd = new ArrayCollection();
        $this->date = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|CommandeLigne[]
     */
    public function getNumCmd(): Collection
    {
        return $this->num_cmd;
    }

    public function addNumCmd(CommandeLigne $numCmd): self
    {
        if (!$this->num_cmd->contains($numCmd)) {
            $this->num_cmd[] = $numCmd;
            $numCmd->setCommande($this);
        }

        return $this;
    }

    public function removeNumCmd(CommandeLigne $numCmd): self
    {
        if ($this->num_cmd->contains($numCmd)) {
            $this->num_cmd->removeElement($numCmd);
            // set the owning side to null (unless already changed)
            if ($numCmd->getCommande() === $this) {
                $numCmd->setCommande(null);
            }
        }

        return $this;
    }

    public function getDemandeur(): ?string
    {
        return $this->demandeur;
    }

    public function setDemandeur(string $demandeur): self
    {
        $this->demandeur = $demandeur;

        return $this;
    }

    public function getMagasinCedant(): ?string
    {
        return $this->magasin_cedant;
    }

    public function setMagasinCedant(string $magasin_cedant): self
    {
        $this->magasin_cedant = $magasin_cedant;

        return $this;
    }

    public function getDestination(): ?string
    {
        return $this->destination;
    }

    public function setDestination(string $destination): self
    {
        $this->destination = $destination;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getSolde(): ?bool
    {
        return $this->solde;
    }

    public function setSolde(bool $solde): self
    {
        $this->solde = $solde;

        return $this;
    }

    public function getNumCommande(): ?string
    {
        return $this->num_commande;
    }

    public function setNumCommande(string $num_commande): self
    {
        $this->num_commande = $num_commande;

        return $this;
    }
}

src/Entity/SavRetour/Picking.php
<?php

namespace App\Entity\SavRetour;

use Doctrine\ORM\Mapping as ORM;

/**
 * Ex table T_SAVRETOUR_PICKING
 *
 * @ORM\Entity(repositoryClass="App\Repository\SavRetour\PickingRepository")
 */
class Picking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SavRetour\Commande", inversedBy="num_cmd")
     * @ORM\JoinColumn(nullable=false)
     */
    private $num_cmd;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $imei;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $gencod;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_heure;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $num_dossier;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumCmd(): ?Commande
    {
        return $this->num_cmd;
    }

    public function setNumCmd(?Commande $num_cmd): self
    {
        $this->num_cmd = $num_cmd;

        return $this;
    }

    public function getImei(): ?string
    {
        return $this->imei;
    }

    public function setImei(string $imei): self
    {
        $this->imei = $imei;

        return $this;
    }

    public function getGencod(): ?string
    {
        return $this->gencod;
    }

    public function setGencod(string $gencod): self
    {
        $this->gencod = $gencod;

        return $this;
    }

    public function getDateHeure(): ?\DateTimeInterface
    {
        return $this->date_heure;
    }

    public function setDateHeure(\DateTimeInterface $date_heure): self
    {
        $this->date_heure = $date_heure;

        return $this;
    }

    public function getNumDossier(): ?string
    {
        return $this->num_dossier;
    }

    public function setNumDossier(string $num_dossier): self
    {
        $this->num_dossier = $num_dossier;

        return $this;
    }
}

templates/picking/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Picking{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="edit d-flex flex-column">
        <div class="d-flex align-items-center justify-content-around">
            <p class="editTitle text-center border-bottom">Picking - sélection de la commande</p>
        </div>
        {{ form_start(form) }}
        <div class="d-flex container justify-content-center mt-4">
            <div class="align-self-center mr-3">{{ form_widget(form.commande) }}</div>
            <div class="align-self-center">{{ form_widget(form.gencod) }}</div>
        </div>
        <div class="d-flex container justify-content-center mt-3 mb-5">
            <div><button class="search btn">Chercher</button></div>
        </div>

        {{ form_end(form) }}

        <table class="table">
            <thead>
                <tr>
                    <th>Num commande</th>
                    <th>Gencod</th>
                    <th>Quantité</th>
                </tr>
            </thead>
            <tbody>

            {% for commande_ligne in commande_lignes %}

            <tr>
                <td>
                    <a href="{{ path('picking', {'id': commande_ligne.id}) }}" class="link tab">{{ commande_ligne.commande.numCommande }}</a>
                </td>
                <td>{{ commande_ligne.gencod }}</td>
                <td>{{ commande_ligne.picking ? : '0'}} / {{ commande_ligne.qte }}</td>

            </tr>

            {% else %}
                <tr>
                    <td colspan="7">Aucune commande à traiter</td>
                </tr>

            {% endfor %}
            </tbody>
        </table>

        <div class="pagination d-flex justify-content-center">
            {{ knp_pagination_render(commande_lignes) }}
        </div>
        <div class="d-flex align-items-center justify-content-center mt-4">
            <a href="{{ path('home') }}" class="navigationButton mx-2" title="Menu principal">
                <i class="fas fa-home fa-2x"></i>
            </a>
            <a href="{{ path('app_logout') }}" class="navigationButton mx-2" title="Déconnexion">
                <i class="fas fa-power-off fa-2x"></i>
            </a>
        </div>
    </div>
</div>


{% endblock %}
{% block javascripts %}
    {{ encore_entry_script_tags('over') }}
{% endblock %}

templates/picking/picking.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% extends 'base.html.twig' %}

{% block title %}Picking{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="edit d-flex flex-column">
        <div class="d-flex align-items-center justify-content-around">
            <p class="editTitle text-center border-bottom">Picking SAV Retour</p>
        </div>
        <div class="d-flex flex-row mt-5">
            <div class="col-6 align-self-center text-center">
                <h6 class="text-center"><b>N° commande</b></h6>
                <p>{{ commande_ligne.commande.numCommande }}</p>
            </div>
            <div class="col-6 text-center">
                <i class="fas fa-barcode fa-6x"></i>
            </div>
        </div>
        {% if commande_ligne.picking < commande_ligne.qte %}
            <form method="post" class="d-flex flex-column mt-2 mb-3">
                <div class="d-flex flex-row justify-content-around py-1">
                    <div class="col-3 d-flex flex-column">
                        <h6 class="text-center"><b>Gencod</b></h6>
                       <p class="mb-0 text-center" id="gencod">{{ commande_ligne.gencod }}</p>
                    </div>
                    <div class="col-3 d-flex flex-column">
                        <h6 class="text-center"><b>Quantité</b></h6>
                        <p class="mb-0 text-center">{{ commande_ligne.picking ? : '0'}} / {{ commande_ligne.qte }}</p>
                    </div>
                    <div class="col-6 align-self-center text-center pt-2">
                        {{ form_start(form) }}
                        {{ form_row(form.gen, {'attr': {'autofocus': true}}) }}
                    </div>
                </div>
                <div class="hidden d-flex row">
                    <div class="col-6">{{ form_row(form.picking) }}</div>
                    <div class="col-6">{{ form_row(form.saveAndNew) }}</div>
                    {{ form_end(form) }}
                </div>

            </form>
                {% else %}
                <div class="d-flex flex-column mt-2 mb-5">
                    <div class="alert d-flex flex-row justify-content-around py-1">
                        <div class="col-3 d-flex flex-column">
                            <h6 class="text-center"><b>Gencod</b></h6>
                            <p class="mb-0 text-center">{{ commande_ligne.gencod }}</p>
                        </div>
                        <div class="col-3 d-flex flex-column">
                            <h6 class="text-center"><b>Quantité</b></h6>
                            <p class="mb-0 text-center">{{ commande_ligne.picking ? : '0'}} / {{ commande_ligne.qte }}</p>
                        </div>
                        <div class="col-6 align-self-center text-center">
                            <a href="{{ path('commande_ligne_index') }}"><button class="btn complete" autofocus><b>La commande est complète !</b></button></a>
                        </div>
                    </div>
                </div>
        {% endif %}
        <div class="d-flex flex-row align-items-center justify-content-center">
            <a href="{{ path('commande_ligne_index') }}" class="pickingButton mr-2 " title="Retour au choix de la commande">
                <i class="fas fa-arrow-circle-left fa-3x"></i>
            </a>
            <a href="{{ path('app_logout') }}" class="pickingButton ml-2" title="Déconnexion">
                <i class="fas fa-power-off fa-3x"></i>
            </a>
        </div>
    </div>
</div>
{% endblock %}
{% block javascripts %}
    {{ encore_entry_script_tags('picking') }}
{% endblock %}